### ISSUE TITLE
MangaFeed quickly crashes when going to a new chapter that hasn't been opened before

### ISSUE THREAD

**Issue by IceKreem** [inorichi/mangafeed#17] opened 2016-01-05 17:23 UTC
Bug described in the title.
Would also like to say the app has come along really nicely, thnxs for creating such a beautiful manga app :)

**Comment by inorichi** [comment] 2016-01-05 17:34
While reading? Or from the chapter list. I also need to know the source (or does it happen on all the sources?)

**Comment by IceKreem** [comment] 2016-01-05 17:38
While reading when I get to the end of the chapter and I swipe to go to the next chapter, it will crash and then go back to the chapter list. On the two sources I use (kissManga and Mangafox), it crashes on both (so it seems to happen across the board).

**Comment by inorichi** [comment] 2016-01-05 17:49
I'm not sure if this will fix it. I guess you have the crash reports enabled and it crashed recently (I got like 10 crashes in the last 24 hours, but it doesn't say too much.

**Comment by IceKreem** [comment] 2016-01-05 18:04
yeah I do, Cool I've downloaded it and no it didn't fix this issue

**Comment by inorichi** [comment] 2016-01-05 18:12
I can't reproduce. Is it a chapter with a lot of pages? Can you try with the webtoon reader?

**Comment by inorichi** [comment] 2016-01-05 18:18
Forget it. There's no way to go to the next chapter ATM in the webtoon reader. :/

**Comment by IceKreem** [comment] 2016-01-05 18:24
Haha I was about to say :P I uploaded a video showing the problem :)
https://youtu.be/RdcN1VO9CmE

**Comment by inorichi** [comment] 2016-01-05 19:06
Do you build the app yourself? If so, comment line 237 in ReaderPresenter: `db.insertChapter(chapter).createObservable().subscribe();`

line 230 could help also `source.savePageList(chapter.url, pageList);`

I tried with the same chapter on 2 devices and a VM, it doesn't crash anywhere. :S

**Comment by IceKreem** [comment] 2016-01-05 19:08
yeah I do build it myself, okay I'll do that :)

**Comment by IceKreem** [comment] 2016-01-05 19:30
oh I know why I have was having this bug, (its still there). In the reader I have it set to right to left as default. When I have it at left to right it works fine. (Totally forgot to mention that!)

**Comment by IceKreem** [comment] 2016-01-05 19:35
Using the latest debug build and it works fine on there. Maybe I did something silly haha :/

**Comment by inorichi** [comment] 2016-01-05 19:36
Yeah, I saw in the video. I also tried with that one. I don't think it's related to that.

**Comment by inorichi** [comment] 2016-01-05 21:16
I think I know the root cause of this. In ChaptersPresenter, line 133, try adding below `onBackpressureBuffer()`

If it still crashes, add the same before `toSortedList` on 146.

Also, on line 63, you can add the error statement (like in the others restartables below) to print the error. It will avoid the crash, but it's not a proper solution.

I still don't know very well how to handle RxJava's backpressure. If none of those works, I will try a different approach without observables.

**Comment by IceKreem** [comment] 2016-01-05 21:23
Ah okay, I will hopefully try it on my other device when I get the time but as I said using the debug build on the readme works fine.So its working somewhere lol

**Comment by inorichi** [comment] 2016-01-06 20:03
I've made some changes for this backpressure issue. Hopefully it won't crash again when changing chapters.

Closing this, reopen it if it happens again.

**Closed by inorichi** 2016-01-06 20:03 UTC
